default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  schema_search_path: public
  template: template0
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: eot_project

test:
  <<: *default
  database: eot_project

production: <%= ENV['DATABASE_URL'] %>