default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  schema_search_path: public
  template: template0
  encoding: unicode
  pool: 5
  
development:
  <<: *default
  database: eot_project

test:
  <<: *default
  database: eot_project

production:
  <<: *default
  database: ddtvriq21o1j65
  username: ybuxueuvsicofi
  password: 7571e269d95bdc728058504a9e54a2e6f267c77c867602edbac6bc4dea0a46c1
  host: ec2-54-197-232-155.compute-1.amazonaws.com
  port: 5432
